# Generated by Django 5.2.8 on 2025-11-23 02:23

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models

import bmcc.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    bmcc.fields.UUIDAutoField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("callsign", models.CharField(blank=True, max_length=64)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("balloon", "Balloon"),
                            ("vehicle", "Vehicle"),
                        ],
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Beacon",
            fields=[
                (
                    "id",
                    bmcc.fields.UUIDAutoField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backend_class_path",
                    models.CharField(
                        choices=[
                            (
                                "bmcc.tracking.backends.bmcc_api.ApiBackend",
                                "BMCC API",
                            ),
                            (
                                "bmcc.tracking.backends.owntracks.OwnTracks",
                                "OwnTracks",
                            ),
                            (
                                "bmcc.tracking.backends.spot.SpotBackend",
                                "SPOT",
                            ),
                        ],
                        max_length=42,
                        verbose_name="backend class path",
                    ),
                ),
                (
                    "backend_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="backend configuration",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beacons",
                        to="tracking.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
        migrations.CreateModel(
            name="Ping",
            fields=[
                (
                    "id",
                    bmcc.fields.UUIDAutoField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reported_at", models.DateTimeField()),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("speed", models.FloatField(blank=True, null=True)),
                ("course", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beacon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings",
                        to="tracking.beacon",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["beacon", "reported_at"],
                        name="tracking_pi_beacon__9ee39d_idx",
                    )
                ],
            },
        ),
    ]
