# Generated by Django 5.2.8 on 2025-11-23 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0001_initial"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ping",
            name="asset",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pings",
                to="tracking.asset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ping",
            name="mission",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pings",
                to="missions.mission",
            ),
            preserve_default=False,
        ),
    ]
