# Generated by Django 5.2.8 on 2025-11-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_ping_asset_ping_mission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beacon",
            name="backend_class_path",
            field=models.CharField(
                choices=[
                    ("bmcc.tracking.backends.bmcc_api.ApiBackend", "BMCC API"),
                    (
                        "bmcc.tracking.backends.owntracks.OwnTracksBackend",
                        "OwnTracks",
                    ),
                    ("bmcc.tracking.backends.spot.SpotBackend", "SPOT"),
                ],
                max_length=49,
                verbose_name="backend class path",
            ),
        ),
    ]
