# Generated by Django 5.2.8 on 2025-11-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_alter_beacon_backend_class_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="ping",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
