# Generated by Django 5.2.8 on 2025-11-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0004_ping_altitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="ping",
            name="accuracy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ping",
            name="altitude",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ping",
            name="speed",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
