# Generated by Django 5.2.8 on 2025-11-23 04:26
from datetime import UTC, datetime

from django.contrib.gis.geos import Point
from django.db import migrations

from .. import constants


def forwards_func(apps, schema_editor):
    Ping = apps.get_model("tracking", "Ping")
    for ping in (
        Ping.objects.using(schema_editor.connection.alias)
        .filter(
            beacon__backend_class_path=constants.BeaconBackendClass.OWNTRACKS,
        )
        .exclude(
            metadata={},
        )
    ):
        ping.position = Point(ping.metadata["lon"], ping.metadata["lat"])
        ping.altitude = ping.metadata.get("alt", None)
        ping.accuracy = ping.metadata.get("acc", None)
        ping.speed = ping.metadata.get("vel", None)
        ping.reported_at = datetime.fromtimestamp(ping.metadata["tst"], tz=UTC)
        ping.save(
            update_fields=[
                "position",
                "altitude",
                "accuracy",
                "speed",
                "reported_at",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "tracking",
            "0005_ping_accuracy_alter_ping_altitude_alter_ping_speed",
        ),
    ]

    operations = [
        migrations.RunPython(
            forwards_func, migrations.RunPython.noop, elidable=True
        )
    ]
