# Generated by Django 5.2.8 on 2025-12-02 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0006_populate_coords"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ping",
            unique_together={("beacon", "reported_at")},
        ),
    ]
