# Generated by Django 5.2.8 on 2025-12-03 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0007_alter_ping_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ping",
            unique_together=set(),
        ),
    ]
