# Generated by Django 5.2.8 on 2025-02-24 00:00

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models

import bmcc.fields


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaunchSiteCandidate",
            fields=[
                (
                    "id",
                    bmcc.fields.UUIDAutoField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("altitude", models.IntegerField(blank=True, null=True)),
                (
                    "intended_launch_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Planned datetime for launch",
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_site_candidates",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "ordering": ["mission", "name"],
            },
        ),
    ]
