# Generated by Django 5.2.8 on 2025-12-03 12:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0004_launchsite_prediction_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="launchsitecandidate",
            name="altitude",
        ),
        migrations.AlterField(
            model_name="launchsitecandidate",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, geography=True, srid=4326
            ),
        ),
    ]
